"""add multi_tenancy

Revision ID: 003af0ccf9dc
Revises: 23ceb0a35e27
Create Date: 2026-06-26 20:53:33.441532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003af0ccf9dc'
down_revision: Union[str, None] = '23ceb0a35e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_relationships', sa.Column('org_id', sa.String(), nullable=False, server_default='default'))
    op.create_index(op.f('ix_asset_relationships_org_id'), 'asset_relationships', ['org_id'], unique=False)
    op.add_column('assets', sa.Column('org_id', sa.String(), nullable=False, server_default='default'))
    op.drop_constraint(op.f('uq_asset_type_value'), 'assets', type_='unique')
    op.create_index(op.f('ix_assets_org_id'), 'assets', ['org_id'], unique=False)
    op.create_unique_constraint('uq_org_asset_type_value', 'assets', ['org_id', 'type', 'value'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_org_asset_type_value', 'assets', type_='unique')
    op.drop_index(op.f('ix_assets_org_id'), table_name='assets')
    op.create_unique_constraint(op.f('uq_asset_type_value'), 'assets', ['type', 'value'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'org_id')
    op.drop_index(op.f('ix_asset_relationships_org_id'), table_name='asset_relationships')
    op.drop_column('asset_relationships', 'org_id')
    # ### end Alembic commands ###
