"""Initial schema

Revision ID: 4cb8f4752233
Revises: 
Create Date: 2026-06-26 17:25:54.503951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cb8f4752233'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('domain', 'subdomain', 'ip_address', 'service', 'certificate', 'technology', name='asset_type'), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', 'archived', name='asset_status'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_asset_type_value')
    )
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_value'), 'assets', ['value'], unique=False)
    op.create_table('asset_relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_asset_id', sa.String(), nullable=False),
    sa.Column('target_asset_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_asset_id', 'target_asset_id', 'relationship_type', name='uq_asset_relationship')
    )
    op.create_index(op.f('ix_asset_relationships_source_asset_id'), 'asset_relationships', ['source_asset_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_target_asset_id'), 'asset_relationships', ['target_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_relationships_target_asset_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_source_asset_id'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    op.drop_index(op.f('ix_assets_value'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
