"""Add indexes

Revision ID: e0f4e8a1d4cd
Revises: 003af0ccf9dc
Create Date: 2026-06-26 21:41:38.736890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f4e8a1d4cd'
down_revision: Union[str, None] = '003af0ccf9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_assets_org_type_status', 'assets', ['org_id', 'type', 'status'], unique=False)
    op.create_index('ix_assets_status', 'assets', ['status'], unique=False)
    op.create_index('ix_assets_type', 'assets', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_type', table_name='assets')
    op.drop_index('ix_assets_status', table_name='assets')
    op.drop_index('ix_assets_org_type_status', table_name='assets')
    # ### end Alembic commands ###
